# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AQXHzTjl5PGRGKV_ljoYzLbFfthtcgY
"""
print("Welcome to kaam chalau calculator :)")
def addition(a, b):
    return a + b

# taking input from user
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

# calling function
result = addition(num1, num2)

# printing result
print("Sum is:", result)
